
#Sample data provided by Rosalind
data = "ATAACTCACGACTGGAGGGGCCACGTAGATAGAGCCTTTAGGCCTGTAAAGATCACACTCATGGAGCCGCTATGGCTATGAGCTTACTCATCATGTTCTACGTAAACTGTTTACAGAAGGTAATGTGAATGAATAGCCAGACGGAAGTCCCTCTCAGGCTATTGGTGGAGACCGGGGGAAGCTGACCGCTGAGCTTAAAATTTCTCGAGAACTTCAATGATACGACGAACGTGTCGGCGTGCCTTCAGAGACCGGGGGGGATGTTTATTTGCTCAGCTACTCTCCTGTAGGATTAACAACTGAATGGGAGTAGTGCTCTCCGACAATAGAGTCAGGCTCGACCCGGGGAAGAACCGGTGACGGGTTAAAAGAGAGAAGAACGTTTCGGAGTAGTCAAGCGGCTTCCTGCGCCGTCGAAGTTGGCCGAAGTAGTAGCGACGCCAGTGTGCGACACCTAAGAGCTTGTACGTGAGGCCGCCAGCGCTCAGATACGGCGAGAATGTTTTACATATCACAAAGCCAGGAGGCTTTGCCGGACACCCAGACTTGTGCGGACACATAAGAAGAATACCGGATGTGCATGGAGCTACAGCCAGCTATTTACTCGTCATCCCCCGGCTAGAGAGTCGAACAGCGATCGATTCAGCCGAGGCGCGTGACAGAAACCGAACTTCATTGAATGTGAAAATGACAGTCGTTAAGCTTCTGCATGAAGCGATAGCAATTTCAAAGCGACAGTTAATATAGTTGATATGGCGTCTTTAAAGTTTAGTATCAGAGAAAGTTGCCAACCGCTACCGGGTAGGTAATAAAGCAGGAAGGAGTGAATCTCAGGAGGAATGCTTCGATCGCGGTAAATCGGCTACCGGACTGTAGG"
#count keeps track of how many times each nucleotide appears
        #A,C,G,T
count = [0,0,0,0]

#increment count as each nucleotide appears
for nuc in data:
    if nuc == "A":
        count[0]+=1
    elif nuc == "C":
        count[1]+=1
    elif nuc == "G":
        count[2]+=1
    elif nuc == "T":
        count[3]+=1

#print in an organized fashion 
print str(count[0]) , " " , str(count[1]) , " " , str(count[2]) , " " + str(count[3])
