data = "ATAACTCACGACTGGAGGGGCCACGTAGATAGAGCCTTTAGGCCTGTAAAGATCACACTCATGGAGCCGCTATGGCTATGAGCTTACTCATCATGTTCTACGTAAACTGTTTACAGAAGGTAATGTGAATGAATAGCCAGACGGAAGTCCCTCTCAGGCTATTGGTGGAGACCGGGGGAAGCTGACCGCTGAGCTTAAAATTTCTCGAGAACTTCAATGATACGACGAACGTGTCGGCGTGCCTTCAGAGACCGGGGGGGATGTTTATTTGCTCAGCTACTCTCCTGTAGGATTAACAACTGAATGGGAGTAGTGCTCTCCGACAATAGAGTCAGGCTCGACCCGGGGAAGAACCGGTGACGGGTTAAAAGAGAGAAGAACGTTTCGGAGTAGTCAAGCGGCTTCCTGCGCCGTCGAAGTTGGCCGAAGTAGTAGCGACGCCAGTGTGCGACACCTAAGAGCTTGTACGTGAGGCCGCCAGCGCTCAGATACGGCGAGAATGTTTTACATATCACAAAGCCAGGAGGCTTTGCCGGACACCCAGACTTGTGCGGACACATAAGAAGAATACCGGATGTGCATGGAGCTACAGCCAGCTATTTACTCGTCATCCCCCGGCTAGAGAGTCGAACAGCGATCGATTCAGCCGAGGCGCGTGACAGAAACCGAACTTCATTGAATGTGAAAATGACAGTCGTTAAGCTTCTGCATGAAGCGATAGCAATTTCAAAGCGACAGTTAATATAGTTGATATGGCGTCTTTAAAGTTTAGTATCAGAGAAAGTTGCCAACCGCTACCGGGTAGGTAATAAAGCAGGAAGGAGTGAATCTCAGGAGGAATGCTTCGATCGCGGTAAATCGGCTACCGGACTGTAGG"

        #A,C,G,T
count = [0,0,0,0]

for nuc in data:
    if nuc == "A":
        count[0]+=1
    if nuc == "C":
        count[1]+=1
    if nuc == "G":
        count[2]+=1
    if nuc == "T":
        count[3]+=1

print str(count[0]) , " " , str(count[1]) , " " , str(count[2]) , " " + str(count[3])
